Creato il file markdown CODE_OF_CONDUCT.md nella directory docs.
softeng2223-inf-uniba/progetto2223-wilkinson pull request #10
Opened 2023-04-06 14:53 UTC by SimonePet

Issue #6 risolta: ho creato il file markdown CODE_OF_CONDUCT.md nella directory docs, richiedo revisione delle modifiche effettuate.

2023-04-06 14:55 UTC, frankcesco reviewed
Approvo il code of conduct della squadra in ogni suo punto.

2023-04-06 14:58 UTC, roccomennea commented
Concordo in pieno con tutti i punti elencati nel codice di condotta da te proposto.

2023-04-06 14:59 UTC, Vincy02 commented
Ho letto e condivido tutti i punti descritti nel file creato.
L'unico aspetto che non condivido è la mancanza di formattazione del file, da rivedere.

2023-04-06 15:34 UTC, Vincy02 requested changes
Ho letto e condivido tutti i punti descritti nel file creato.
L'unico aspetto che non condivido è la mancanza di formattazione del file, da rivedere.

2023-04-06 15:38 UTC, SimonePet commented
Okay provvedo subito

2023-04-06 15:48 UTC, Vincy02 approved these changes
Approvo formattazione ora.
Riconfermo di condividere tutti i punti descritti nel file creato.

2023-04-06 15:50 UTC, roccomennea approved these changes
Concordo in pieno con tutti i punti elencati nel codice di condotta da te proposto.
Giusta la decisione di inserire della formattazione al testo.

2023-04-07 15:35 UTC, frankcesco approved these changes
Dopo aver visto i cambiamenti richiesti dagli altri reviewers, ho visto che è stata ulteriormente ottimizzata la formattazione del testo.

2023-04-07 15:35 UTC, MattMic02 approved these changes
Perfetto, le modifiche rispecchiano quanto ho chiesto. Ho visto che è stata ulteriormente ottimizzata anche la formattazione del testo.

2023-04-07 15:37 UTC, merged